server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thunberg_test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Guilin3546!
  cache:
    redis:
      #使用前缀
      use-key-prefix: true
      #redis过期时间
      time-to-live: 60s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      #schema: classpath:/sql/schema.sql
  type-aliases-package: edu.uog.thunbergTest.model.entity